name: CI/CD for Chrome Extension

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint JS
        run: |
          npm install eslint prettier --save-dev
          npx eslint . --ext .js
          npx prettier --check .

      - name: Build ZIP
        run: |
          mkdir dist
          zip -r dist/llm-detector.zip . -x "*.git*" -x "dist/*" -x "*.DS_Store"

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4.6
        with:
          name: llm-detector-extension
          path: dist/llm-detector.zip

  publish:
    needs: lint-and-build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rebuild ZIP
        run: |
          mkdir dist
          zip -r dist/llm-detector.zip . -x "*.git*" -x "dist/*" -x "*.DS_Store"

      - name: Publish to Chrome Web Store
        uses: PlasmoHQ/chrome-extension-upload-action@v1
        with:
          client_id: ${{ secrets.CHROME_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
          zip: dist/llm-detector.zip
